kubernetes:
  host: https://kubernetes.default

reloader:
  isArgoRollouts: false
  isOpenshift: false
  ignoreSecrets: false
  ignoreConfigMaps: false
  reloadOnCreate: false
  syncAfterRestart: false
  reloadStrategy: default # Set to default, env-vars or annotations
  ignoreNamespaces: "" # Comma separated list of namespaces to ignore
  namespaceSelector: "" # Comma separated list of k8s label selectors for namespaces selection
  resourceLabelSelector: "" # Comma separated list of k8s label selectors for configmap/secret selection
  logFormat: "" #json
  watchGlobally: true
  deployment:
    replicas: 1
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: "Infra-Services"
              operator: In
              values:
              - "true"


    resources: {}
    pod:
      annotations: 
        co.elastic.logs/enabled: "true"

  serviceMonitor:
    enabled: ${enable_service_monitor}
    namespace: reloader
    interval: 10s
    timeout: 30s
    labels: 
      release: prometheus-operator

  
  podDisruptionBudget:
    enabled: true
    minAvailable: 1