apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: cluster-azure-store
spec:
  provider:
    azurekv:
      authType: WorkloadIdentity
      vaultUrl: "https://prod-skaf-exsecrets.vault.azure.net/"
      serviceAccountRef:
        name: external-secrets
        namespace: secrets