apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mysql-pass
spec:
  secretStoreRef:
    name: cluster-azure-store
    kind: ClusterSecretStore
  target:
    name: mysql-pass           
    creationPolicy: Owner
  data:
  - secretKey: password
    remoteRef:
      key: password
