apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: test2
spec:
  secretStoreRef:
    name: azure-store
    kind: SecretStore
  target:
    name: all-secrets           # name of the k8s Secret to be created
    creationPolicy: Owner
  dataFrom:
  - find:
      name:
        regexp: "^test"