---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: azure-store
spec:
  provider:
    azurekv:
      authType: WorkloadIdentity
      vaultUrl: "https://test-anoushka-exsecrets.vault.azure.net/"
      serviceAccountRef:
        name: external-secrets